### ISSUE TITLE
How can we use this data

### ISSUE THREAD

**Issue by mrvamsidhar** [nccgroup/azucar#1]
First of all thanks for putting this code. I am trying for this kind of Audits on Azure resources. One questions is, how can I make use of this data. Lets, say in classic endpoints data audit, I need to call out Remote Desktop endpoint as non-compliant. Your code is almost pulling all the data but is not saying if the resource is compliant or not. How can I achieve this?

**Comment by shivankar-madaan** [comment]
Hi @mrvamsidhar 
    You could use the Azure CIS-benchmark's to audit your Azure cloud,with the data you got from Azucar
https://azure.microsoft.com/mediahandler/files/resourcefiles/cis-microsoft-azure-foundations-security-benchmark/CIS_Microsoft_Azure_Foundations_Benchmark_v1.0.0.pdf

Hope it helps!!
Cheers.

**Comment by silverhack** [comment]
Hi all, 

You could also create a custom plugin to extract or analyse any kind of asset within your Azure subscription
