### ISSUE TITLE
Exception calling "LoadFrom" with "1" argument(s): "Could not load file or assembly

### ISSUE THREAD

**Issue by ahmedsherif** [nccgroup/azucar#10]
Hi, 

I came up with the following error: 

By Calling: ` .\azucar.ps1`

`Exception calling "LoadFrom" with "1" argument(s): "Could not load file or assembly 'file:///C:\azucar-master\Libs\Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms.dll' or one of its dependencies. Operation is not supported.`

**Comment by raul5660** [comment]
try this? 
https://stackoverflow.com/questions/34400546/could-not-load-file-or-assembly-operation-is-not-supported-exception-from-hres/34400547

**Comment by ismailakinkunmi** [comment]
uninstall entityframework restart the project and reinstall entityframework.

**Comment by ghardy2k** [comment]
thanks, ismail.....the trick was restarting after removing.   you rock!

**Comment by NgocSon288** [comment]
ismailakinkunmi thanks!
