### ISSUE TITLE
Excel report format

### ISSUE THREAD

**Issue by hax0rgb** [nccgroup/azucar#3]
I was able to get the CSV, JSON and XML reports. However, not the EXCEL report. How can we generate the report as shown in the [sample report](https://github.com/nccgroup/azucar/files/1915480/Azucar_Report_20170308.xlsx) .

I used the `-ExportTo CSV,JSON,XML,EXCEL` command to export into respective formats. However, EXCEL report format folder is always empty.

**Comment by silverhack** [comment]
Could you please let me know which Office version do you have?

**Comment by hax0rgb** [comment]
I am using Microsoft Office 2016 for Mac.

Microsoft Excel version: 16.16.6

**Comment by silverhack** [comment]
Hi, 

Mac is not supported. Only Windows is supported
