### ISSUE TITLE
Unable to print the report in CSV and Excel formats

### ISSUE THREAD

**Issue by challs1** [nccgroup/azucar#4]
I was able to get the JSON and XML reports. However, not the EXCEL and CSV report. How can we generate the report as shown in the sample report .

I used the -ExportTo CSV,JSON,XML,EXCEL command to export into respective formats. However, EXCEL report format folder is always empty.

**Comment by silverhack** [comment]
The Azucar tool has a parameter called ExportTo which can be used to export output to CSV
