### ISSUE TITLE
Error running on Mac

### ISSUE THREAD

**Issue by sfc-gh-osinger** [nccgroup/azucar#5]
Hoping to be able to run this on Powershell for Mac. Getting this error, is IE really required or can this be tweaked to support Mac? 

Get-ItemProperty : Cannot find drive. A drive with the name 'HKLM' does not exist.
At ~/azucar/Azucar.ps1:274 char:69
+ ... gumentList (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Internet Explo ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (HKLM:String) [Get-ItemProperty], DriveNotFoundException
+ FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.GetItemPropertyCommand
 
New-Object : Exception calling ".ctor" with "4" argument(s): "Version's parameters must be greater than or equal to zero.
Parameter name: build"
At ~/azucar/Azucar.ps1:275 char:18
+     $ieVersion = New-Object -TypeName System.Version -ArgumentList (
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
+ FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand
 
[Exception][Main][286]:Internet Explorer 11 or later required. Current IE version is '0.0'.

**Comment by silverhack** [comment]
Hi, 
Sorry, but at the moment only windows is supported by the tool.
